//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoatOfRussiaMobileApp.Models
{
    using System;
	using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int EventId { get; set; }
        public byte[] Data { get; set; }
        public System.DateTime DateEdit { get; set; }
        public System.DateTime DateApproval { get; set; }
        public int StatusId { get; set; }
        public int TypeId { get; set; }
        public int SectionId { get; set; }
        public int AuthorId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Event Event { get; set; }
        public virtual SectionMaterial SectionMaterial { get; set; }
        public virtual StatusMaterial StatusMaterial { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
    }
}
