//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
 	 using Newtonsoft.Json; 
 	 using System.Linq;
    using System.Collections.Generic;
    using WpfApp1.Services;

    public partial class Comments
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        [JsonIgnore]
        public virtual Material Document
        {
            get
            {
            return DbContext.Materials.FirstOrDefault(x=>x.Id == DocumentId);
            }
            set
            {
                DocumentId = value.Id;
            }
    
        }
        
        public string Text { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public int AuthorId { get; set; }
        [JsonIgnore]
        public virtual Employee Author
        {
            get
            {
            return DbContext.Employees.FirstOrDefault(x=>x.Id == AuthorId);
            }
            set
            {
                AuthorId = value.Id;
            }
    
        }
        
    
        public virtual Employee Employee { get; set; }
        public virtual Material Material { get; set; }
    }
}
