//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
 	 using Newtonsoft.Json; 
 	 using System.Linq;
    using System.Collections.Generic;
    using WpfApp1.Services;

    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventEmployee = new HashSet<EventEmployee>();
            this.PrimaryPersonsEvent = new HashSet<PrimaryPersonsEvent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeEventId { get; set; }
        [JsonIgnore]
        public virtual TypeEvent TypeEvent
        {
            get
            {
            return DbContext.TypeEvents.FirstOrDefault(x=>x.Id == TypeEventId);
            }
            set
            {
                TypeEventId = value.Id;
            }
    
        }
        
        public Nullable<int> StatusEventId { get; set; }
        [JsonIgnore]
        public virtual StatusEvent StatusEvent
        {
            get
            {
            return DbContext.StatusEvents.FirstOrDefault(x=>x.Id == StatusEventId);
            }
            set
            {
                StatusEventId = value.Id;
            }
    
        }
        
        public System.DateTime DateTimeStart { get; set; } = DateTime.Now;
        public string ShortDescription { get; set; }
        public Nullable<int> AuthorId { get; set; }
        [JsonIgnore]
        public virtual Employee Author
        {
            get
            {
            return DbContext.Employees.FirstOrDefault(x=>x.Id == AuthorId);
            }
            set
            {
                AuthorId = value.Id;
            }
    
        }
        
        public System.DateTime DateTimeEnd { get; set; } = DateTime.Now.AddDays(1);

        public virtual Employee Employee { get; set; }
     
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventEmployee> EventEmployee { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryPersonsEvent> PrimaryPersonsEvent { get; set; }
    }
}
