//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
 	 using Newtonsoft.Json; 
 	 using System.Linq;
    using System.Collections.Generic;
    using WpfApp1.Services;

    public partial class EventEmployee
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        [JsonIgnore]
        public virtual Event Event
        {
            get
            {
            return DbContext.Events.FirstOrDefault(x=>x.Id == EventId);
            }
            set
            {
                EventId = value.Id;
            }
    
        }
        
        public int EmployeeId { get; set; }
        [JsonIgnore]
        public virtual Employee Employee
        {
            get
            {
            return DbContext.Employees.FirstOrDefault(x=>x.Id == EmployeeId);
            }
            set
            {
                EmployeeId = value.Id;
            }
    
        }
        
    
     
     
    }
}
