//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoatOfRussiaApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoatOfRussiaEntities : DbContext
    {
        public RoatOfRussiaEntities()
            : base("name=RoatOfRussiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence> Absence { get; set; }
        public virtual DbSet<Cabinet> Cabinet { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventEmployee> EventEmployee { get; set; }
        public virtual DbSet<EventResponsiblePerson> EventResponsiblePerson { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<SectionMaterial> SectionMaterial { get; set; }
        public virtual DbSet<StatusEvent> StatusEvent { get; set; }
        public virtual DbSet<StatusMaterial> StatusMaterial { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeEvent> TypeEvent { get; set; }
        public virtual DbSet<TypeMaterial> TypeMaterial { get; set; }
        public virtual DbSet<Vacation> Vacation { get; set; }
        public virtual DbSet<WorkingCalendar> WorkingCalendar { get; set; }
    }
}
